### PR TITLE
feat: add login-and-signup page

### PR DESCRIPTION
**Pull request by Maianki**
## Added login/sign up page and navbar component

This PR includes

- [x] Login page
- [x] Sign up page
- [x] Navbar component
### Thanks for reviewing my PR

### CODE REVIEW

**Review by foolhardy21 — APPROVED** [review]
The code structure looks good. One suggestion would be to add a `alt` attribute for every `<Avatar />`. Good to go ahead.

**Review by anik31 — APPROVED** [review]
The UI looks great. Nice that you're using chakra ui.

**Comment by Maianki** [comment]
> The code structure looks good. One suggestion would be to add a `alt` attribute for every `<Avatar />`. Good to go ahead.

Sure I will do it thanks for reviewing

**Comment by Maianki** [comment]
Thanks for reviewing @anik31 @foolhardy21

**Pull request merged**
